// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webProject.Data;

#nullable disable

namespace webProject.Migrations
{
    [DbContext(typeof(FitnessDbContext))]
    [Migration("20251211170356_düzeltme")]
    partial class düzeltme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("webProject.Models.AntHizmet", b =>
                {
                    b.Property<int>("AntID")
                        .HasColumnType("integer");

                    b.Property<int>("HizID")
                        .HasColumnType("integer");

                    b.Property<int>("AntrenorID")
                        .HasColumnType("integer");

                    b.Property<int>("HizmetID")
                        .HasColumnType("integer");

                    b.HasKey("AntID", "HizID");

                    b.HasIndex("AntrenorID");

                    b.HasIndex("HizmetID");

                    b.ToTable("AtrHizmet");
                });

            modelBuilder.Entity("webProject.Models.AntMusaitlik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AntID")
                        .HasColumnType("integer");

                    b.Property<int>("AntrenorID")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("BaslangicSaat")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("BitisSaat")
                        .HasColumnType("interval");

                    b.Property<string>("Gun")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("AntrenorID");

                    b.ToTable("AtrMusaitlik");
                });

            modelBuilder.Entity("webProject.Models.Antrenor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UzmanlıkAlanı")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Antrenor");
                });

            modelBuilder.Entity("webProject.Models.HizSalon", b =>
                {
                    b.Property<int>("HizID")
                        .HasColumnType("integer");

                    b.Property<int>("SalID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric");

                    b.Property<int>("HizmetID")
                        .HasColumnType("integer");

                    b.Property<int>("SalonID")
                        .HasColumnType("integer");

                    b.Property<int>("Sure")
                        .HasColumnType("integer");

                    b.HasKey("HizID", "SalID");

                    b.HasIndex("HizmetID");

                    b.HasIndex("SalonID");

                    b.ToTable("HizSalon");
                });

            modelBuilder.Entity("webProject.Models.Hizmet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric");

                    b.Property<int>("SureDaikia")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Hizmet");
                });

            modelBuilder.Entity("webProject.Models.Randevu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AtrenorID")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("BaslangicSaat")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("BitisSaat")
                        .HasColumnType("interval");

                    b.Property<int>("HizmetID")
                        .HasColumnType("integer");

                    b.Property<bool>("OnayDurumu")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("numeric");

                    b.Property<int>("UyeID")
                        .HasColumnType("integer");

                    b.Property<int>("salonID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AtrenorID");

                    b.HasIndex("HizmetID");

                    b.HasIndex("UyeID");

                    b.HasIndex("salonID");

                    b.ToTable("Randevu");
                });

            modelBuilder.Entity("webProject.Models.Salon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CalismaSaatleri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Salon");
                });

            modelBuilder.Entity("webProject.Models.Uye", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Uye");
                });

            modelBuilder.Entity("webProject.Models.AntHizmet", b =>
                {
                    b.HasOne("webProject.Models.Antrenor", "Antrenor")
                        .WithMany("AntHizmetler")
                        .HasForeignKey("AntrenorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webProject.Models.Hizmet", "Hizmet")
                        .WithMany("AtrHizmetler")
                        .HasForeignKey("HizmetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrenor");

                    b.Navigation("Hizmet");
                });

            modelBuilder.Entity("webProject.Models.AntMusaitlik", b =>
                {
                    b.HasOne("webProject.Models.Antrenor", "Antrenor")
                        .WithMany("Musaitlik")
                        .HasForeignKey("AntrenorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrenor");
                });

            modelBuilder.Entity("webProject.Models.HizSalon", b =>
                {
                    b.HasOne("webProject.Models.Hizmet", "Hizmet")
                        .WithMany("HizSalonlar")
                        .HasForeignKey("HizmetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webProject.Models.Salon", "Salon")
                        .WithMany("HizSalonlar")
                        .HasForeignKey("SalonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hizmet");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("webProject.Models.Randevu", b =>
                {
                    b.HasOne("webProject.Models.Antrenor", "atrenor")
                        .WithMany("Randevular")
                        .HasForeignKey("AtrenorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webProject.Models.Hizmet", "hizmet")
                        .WithMany("Randevular")
                        .HasForeignKey("HizmetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webProject.Models.Uye", "uye")
                        .WithMany()
                        .HasForeignKey("UyeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webProject.Models.Salon", "salon")
                        .WithMany("Randevular")
                        .HasForeignKey("salonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("atrenor");

                    b.Navigation("hizmet");

                    b.Navigation("salon");

                    b.Navigation("uye");
                });

            modelBuilder.Entity("webProject.Models.Antrenor", b =>
                {
                    b.Navigation("AntHizmetler");

                    b.Navigation("Musaitlik");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("webProject.Models.Hizmet", b =>
                {
                    b.Navigation("AtrHizmetler");

                    b.Navigation("HizSalonlar");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("webProject.Models.Salon", b =>
                {
                    b.Navigation("HizSalonlar");

                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
